<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_Input.Password</name>
   <tag></tag>
   <elementGuidId>ffbe6856-b975-45dd-8ad0-ad5342626c88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AccountLoginIndexPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'password' and @name = 'Input.Password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>77aac2f6-3184-444f-8ce9-d7731545d60a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>71ea26f0-c69a-4b4c-ac2a-6c6968bd849b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccountLoginIndexPassword</value>
      <webElementGuid>4aa8c42c-d7fa-47fd-98cb-c06225b7dfe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-login</value>
      <webElementGuid>784d59af-9a91-454a-8996-6449ff88b9e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>40bd5c9b-8220-4e73-865b-c5d0d45ba94d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d9d81297-77b4-4cf1-b270-9a65b9267940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Password field is required.</value>
      <webElementGuid>cd102a3d-976b-466a-8654-fdc0db93da1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Input.Password</value>
      <webElementGuid>41b8a0df-ebc0-41d1-955c-eabb7a910cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccountLoginIndexPassword&quot;)</value>
      <webElementGuid>2e940a67-37a7-42ba-9d8c-56a0148833b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'Input.Password']</value>
      <webElementGuid>a086c3df-c1d1-449f-96e0-ffc8d0bc4a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccountLoginIndexPassword']</value>
      <webElementGuid>2221eac9-be89-4e21-b39c-b1fb55aa259a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/section[2]/div/div[2]/div/div/form/div[3]/input</value>
      <webElementGuid>788f0160-14ec-4f88-913b-9462991e071c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>d41ce79d-eff7-4891-8a0a-ee38cb65d4cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
