<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Retail Flutter Pos Client_Input.Organization</name>
   <tag></tag>
   <elementGuidId>7b441fed-df60-4090-a080-842cfd9c99d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AccountLoginIndexOrganization</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'text' and @name = 'Input.Organization']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0347aab-f462-484b-a719-b556cf46c274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-login</value>
      <webElementGuid>f1555171-3174-4d90-bff1-91daafa07033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccountLoginIndexOrganization</value>
      <webElementGuid>f8524f52-39ad-4702-b30a-56fa56f48673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>be752b9a-ea4a-4199-8198-ad1dafaae4d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ccd153d2-aa01-41c2-ae8c-2e36d11ffc0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Organization field is required.</value>
      <webElementGuid>f4d0701d-7a19-46b0-b113-2c98600bc038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Input.Organization</value>
      <webElementGuid>b8522abe-24cf-4102-8135-0f4dd8d918cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccountLoginIndexOrganization&quot;)</value>
      <webElementGuid>3e1d239c-347e-4948-b7ce-20922165d818</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Input.Organization']</value>
      <webElementGuid>f387d30b-7695-4579-965c-ad6bdb2b4d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccountLoginIndexOrganization']</value>
      <webElementGuid>3c2341fb-bc01-43fa-8c5e-757404e22408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/section[2]/div/div[2]/div/div/form/div/input</value>
      <webElementGuid>9e3836b7-eb7e-4264-a087-c53211a91e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>c3ac121e-dd73-436b-b67c-8698c2da8c67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
