<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn-AddQuantity</name>
   <tag></tag>
   <elementGuidId>fab90ac8-0abb-4d89-aceb-70376eb44f95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//flt-semantics[@role = 'button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>flt-semantics[aria-label*='Stuks']:nth-child(1) flt-semantics-container > flt-semantics:nth-child(5)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>flt-semantics</value>
      <webElementGuid>d21c45fc-4db6-4ca1-813b-a98a88866f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flt-semantic-node-52</value>
      <webElementGuid>896a9852-2c65-461b-8468-c61d0116636c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>403ed9be-5524-44f2-be6e-49426c025e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>23c783a8-3cfa-440a-a3f8-60078596dbbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/flt-semantics-host[1]/flt-semantics[@id=&quot;flt-semantic-node-0&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-1&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-11&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-12&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-13&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-19&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-30&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-23&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-43&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-53&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-44&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-52&quot;]</value>
      <webElementGuid>3cd6afe1-ac9c-427b-a673-22c5d87b5329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Retail by Aiden/flt-glass-pane</value>
      <webElementGuid>eccef6d1-0705-4da7-a540-00ebabef838c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d5d6a6c3-7832-44fb-8173-327c2ae1af84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//flt-semantics[@role = 'button']</value>
      <webElementGuid>fc45ec85-b523-44ad-986f-de4461c8665b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flt-semantics[@id='flt-semantic-node-44']/flt-semantics-container/flt-semantics[5]</value>
      <webElementGuid>a072d506-9d9a-47cc-934b-6ea0d0591c6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
