<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-Finish</name>
   <tag></tag>
   <elementGuidId>cb69fb88-4688-49bb-8b62-1fa9f8163067</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>flt-semantics[aria-label*='Finish']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Retail by Aiden/flt-glass-pane</value>
      <webElementGuid>274a1d8f-276d-48ab-a2b2-0c846cdbaa5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>71838f67-cc98-4e06-8f0f-01454c97e581</webElementGuid>
   </webElementProperties>
</WebElementEntity>
