<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>flt-glass-pane</name>
   <tag></tag>
   <elementGuidId>a392a4cb-d871-43ce-b00e-8d4aefc0cb16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>flt-glass-pane</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//flt-glass-pane</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>flt-glass-pane</value>
      <webElementGuid>d4032230-5dd5-445e-a68a-ba2c11e126b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/flt-glass-pane[1]</value>
      <webElementGuid>2b6f2edd-aac7-40dd-a8f9-5680d4a43e08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//flt-glass-pane</value>
      <webElementGuid>7e9c6e85-ddac-4802-9bcf-2b5065c98af4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
