<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input-searchitem</name>
   <tag></tag>
   <elementGuidId>dc9a1c91-9167-43a6-aa8b-64f846c2b05c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@aria-label = 'Search items...']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>flt-semantics>input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b0c9c51-1c6a-4f71-813e-55b204ee89e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a8e236de-2a6d-4bc9-b39f-e07b01807efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>8976f6a5-14ac-42bc-9162-b3c589ed99e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1458f1ff-0e9c-4daa-bf9a-08a7b6d9851b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-semantics-role</name>
      <type>Main</type>
      <value>text-field</value>
      <webElementGuid>8288725a-8bca-4c6b-8acc-39d8f8cfc66c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search items...</value>
      <webElementGuid>6401a533-d7a9-462e-ad45-26d0cd3b4abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/flt-semantics-host[1]/flt-semantics[@id=&quot;flt-semantic-node-0&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-1&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-11&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-12&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-13&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-19&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-30&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-21&quot;]/input[1]</value>
      <webElementGuid>df393fef-89bd-4f98-91b7-f4c38c725d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Retail by Aiden/flt-glass-pane</value>
      <webElementGuid>9f89ae2f-c23f-47da-a9a6-7ebdd7b561e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>872d8e9b-300b-47b7-a828-80069e2610e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@aria-label = 'Search items...']</value>
      <webElementGuid>b66cbcd3-ce40-42ea-a7fa-dc703e383ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flt-semantics[@id='flt-semantic-node-21']/input</value>
      <webElementGuid>b051cda0-2128-4a78-a566-5629340fe0da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
